# Translations template for glance.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the glance project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance 2014.2.dev51.g3419ecc\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-07-06 06:00+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: glance/location.py:79
msgid "Invalid location"
msgstr ""

#: glance/location.py:273
msgid "Invalid locations"
msgstr ""

#: glance/location.py:279
#, python-format
msgid "Original locations is not empty: %s"
msgstr ""

#: glance/location.py:342 glance/common/exception.py:345
msgid "No image data could be found"
msgstr ""

#: glance/location.py:351
#, python-format
msgid "Get image %(id)s data failed: %(err)s."
msgstr ""

#: glance/location.py:356
#, python-format
msgid "Glance tried all locations to get data for image %s but all have failed."
msgstr ""

#: glance/notifier.py:178 glance/api/common.py:86
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr ""

#: glance/notifier.py:195 glance/api/v1/upload_utils.py:185
#: glance/api/v2/image_data.py:111
#, python-format
msgid "Image storage media is full: %s"
msgstr ""

#: glance/notifier.py:199 glance/api/v1/upload_utils.py:194
#: glance/api/v2/image_data.py:132
#, python-format
msgid "Insufficient permissions on image storage media: %s"
msgstr ""

#: glance/notifier.py:204
#, python-format
msgid "Cannot save data for image %(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:211
#, python-format
msgid "Unable to upload duplicate image data for image%(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:218
#, python-format
msgid "Not allowed to upload image data for image %(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:224
#, python-format
msgid ""
"Image %(image_id)s could not be found after upload. The image may have "
"been deleted during the upload: %(error)s"
msgstr ""

#: glance/notifier.py:232
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to HTTP error: "
"%(error)s"
msgstr ""

#: glance/notifier.py:239
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to internal error:"
" %(error)s"
msgstr ""

#: glance/schema.py:59
#, python-format
msgid "custom properties (%(props)s) conflict with base properties"
msgstr ""

#: glance/scrubber.py:38 glance/store/__init__.py:46
msgid ""
"Directory that the scrubber will use to track information about what to "
"delete. Make sure this is set in glance-api.conf and glance-"
"scrubber.conf."
msgstr ""

#: glance/scrubber.py:43 glance/store/__init__.py:56
msgid "The amount of time in seconds to delay before performing a delete."
msgstr ""

#: glance/scrubber.py:46
msgid ""
"A boolean that determines if the scrubber should clean up the files it "
"uses for taking data. Only one server in your deployment should be "
"designated the cleanup host."
msgstr ""

#: glance/scrubber.py:51
msgid ""
"Items must have a modified time that is older than this value in order to"
" be candidates for cleanup."
msgstr ""

#: glance/scrubber.py:135
#, python-format
msgid "%s file can not be read."
msgstr ""

#: glance/scrubber.py:159
#, python-format
msgid "%s file can not be wrote."
msgstr ""

#: glance/scrubber.py:184 glance/api/v1/images.py:1040
#, python-format
msgid "Failed to find image to delete: %(e)s"
msgstr ""

#: glance/scrubber.py:216
#, python-format
msgid "%s directory does not exist."
msgstr ""

#: glance/scrubber.py:363
#, python-format
msgid "Starting Daemon: wakeup_time=%(wakeup_time)s threads=%(threads)s"
msgstr ""

#: glance/scrubber.py:377
msgid "Daemon Shutdown on KeyboardInterrupt"
msgstr ""

#: glance/scrubber.py:389
#, python-format
msgid "Initializing scrubber with configuration: %s"
msgstr ""

#: glance/scrubber.py:413
#, python-format
msgid "Can not %s scrub jobs from queue."
msgstr ""

#: glance/scrubber.py:437
#, python-format
msgid "Scrubbing image %(id)s from %(count)d locations."
msgstr ""

#: glance/scrubber.py:465
#, python-format
msgid "Failed to delete URI from image %(image_id)s"
msgstr ""

#: glance/scrubber.py:477
#, python-format
msgid "%s file is not exists."
msgstr ""

#: glance/scrubber.py:482
#, python-format
msgid "%s file contains conflicting cleanup timestamp."
msgstr ""

#: glance/scrubber.py:501
#, python-format
msgid "%s file can not be created."
msgstr ""

#: glance/scrubber.py:516
#, python-format
msgid "Getting images deleted before %s"
msgstr ""

#: glance/api/authorization.py:129 glance/api/authorization.py:140
#, python-format
msgid "You cannot get image member for %s"
msgstr ""

#: glance/api/authorization.py:148
#, python-format
msgid "You cannot delete image member for %s"
msgstr ""

#: glance/api/authorization.py:157
#, python-format
msgid "You cannot add image member for %s"
msgstr ""

#: glance/api/authorization.py:166
#, python-format
msgid "You cannot update image member %s"
msgstr ""

#: glance/api/authorization.py:185
#, python-format
msgid "You are not permitted to create images owned by '%s'."
msgstr ""

#: glance/api/authorization.py:203
msgid "You are not permitted to create image members for the image."
msgstr ""

#: glance/api/authorization.py:208 glance/api/authorization.py:399
msgid "Public images do not have members."
msgstr ""

#: glance/api/authorization.py:224
#, python-format
msgid "You are not permitted to modify '%(attr)s' on this %(resource)s."
msgstr ""

#: glance/api/authorization.py:234
msgid "You are not permitted to modify locations for this image."
msgstr ""

#: glance/api/authorization.py:258
#, python-format
msgid "You are not permitted to modify '%s' on this image."
msgstr ""

#: glance/api/authorization.py:262
msgid "You are not permitted to modify this image."
msgstr ""

#: glance/api/authorization.py:275
msgid "You are not permitted to modify tags on this image."
msgstr ""

#: glance/api/authorization.py:316
msgid "You are not permitted to delete this image."
msgstr ""

#: glance/api/authorization.py:327
msgid "You are not permitted to upload data for this image."
msgstr ""

#: glance/api/authorization.py:364 glance/api/authorization.py:368
#: glance/api/authorization.py:372
msgid "You are not permitted to set status on this task."
msgstr ""

#: glance/api/authorization.py:431
#, python-format
msgid "You are not permitted to create this task with owner as: %s"
msgstr ""

#: glance/api/common.py:49
#, python-format
msgid ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"
msgstr ""

#: glance/api/common.py:55
#, python-format
msgid ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"
msgstr ""

#: glance/api/common.py:60
#, python-format
msgid "Corrupt image download for image %(image_id)s"
msgstr ""

#: glance/api/common.py:112
#, python-format
msgid "Invalid value for option user_storage_quota: %(users_quota)s"
msgstr ""

#: glance/api/common.py:157
#, python-format
msgid ""
"User %(user)s attempted to upload an image of unknown size that will "
"exceeed the quota. %(remaining)d bytes remaining."
msgstr ""

#: glance/api/common.py:166
#, python-format
msgid ""
"User %(user)s attempted to upload an image of size %(size)d that will "
"exceeed the quota. %(remaining)d bytes remaining."
msgstr ""

#: glance/api/policy.py:34
msgid "The location of the policy file."
msgstr ""

#: glance/api/policy.py:36
msgid "The default policy to use."
msgstr ""

#: glance/api/policy.py:96
msgid "Unable to find policy file"
msgstr ""

#: glance/api/policy.py:220 glance/quota/__init__.py:344
#, python-format
msgid "Invalid locations: %s"
msgstr ""

#: glance/api/middleware/cache.py:57
msgid "Initialized image cache middleware"
msgstr ""

#: glance/api/middleware/cache.py:132
#, python-format
msgid ""
"Image cache contained image file for image '%s', however the registry did"
" not contain metadata for that image!"
msgstr ""

#: glance/api/middleware/cache.py:230
#, python-format
msgid "could not find %s"
msgstr ""

#: glance/api/middleware/cache.py:250
msgid "Checksum header is missing."
msgstr ""

#: glance/api/middleware/cache_manage.py:72
msgid "Initialized image cache management middleware"
msgstr ""

#: glance/api/middleware/context.py:28
msgid ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."
msgstr ""

#: glance/api/middleware/context.py:33
msgid "Role used to identify an authenticated user as administrator."
msgstr ""

#: glance/api/middleware/context.py:36
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""

#: glance/api/middleware/context.py:52
msgid "Unable to retrieve request id from context"
msgstr ""

#: glance/api/middleware/context.py:109
msgid "Invalid service catalog json."
msgstr ""

#: glance/api/middleware/gzip.py:33
msgid "Initialized gzip middleware"
msgstr ""

#: glance/api/middleware/version_negotiation.py:41
#, python-format
msgid "Determining version of request: %(method)s %(path)s Accept: %(accept)s"
msgstr ""

#: glance/api/v1/controller.py:81
#, python-format
msgid "Store for image_id not found: %s"
msgstr ""

#: glance/api/v1/images.py:76
#, python-format
msgid "Invalid disk format '%s' for image."
msgstr ""

#: glance/api/v1/images.py:81
#, python-format
msgid "Invalid container format '%s' for image."
msgstr ""

#: glance/api/v1/images.py:86
#, python-format
msgid "Image name too long: %d"
msgstr ""

#: glance/api/v1/images.py:97
msgid ""
"Invalid mix of disk and container formats. When setting a disk or "
"container format to one of 'aki', 'ari', or 'ami', the container and disk"
" formats must match."
msgstr ""

#: glance/api/v1/images.py:175
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(num)s, Maximum: %(quota)s"
msgstr ""

#: glance/api/v1/images.py:338
msgid "This operation is currently not permitted on Glance images details."
msgstr ""

#: glance/api/v1/images.py:389
#, python-format
msgid "Bad value passed to filter %(filter)s got %(val)s"
msgstr ""

#: glance/api/v1/images.py:544
#, python-format
msgid "Failed to reserve image. Got error: %(e)s"
msgstr ""

#: glance/api/v1/images.py:706
msgid "Triggering asynchronous copy from external source"
msgstr ""

#: glance/api/v1/images.py:849
msgid "Forbidden to update deleted image."
msgstr ""

#: glance/api/v1/images.py:860
#, python-format
msgid "Forbidden to modify '%s' of active image."
msgstr ""

#: glance/api/v1/images.py:878
msgid "Cannot upload to an unqueued image"
msgstr ""

#: glance/api/v1/images.py:902
msgid "Attempted to update Location field for an image not in queued status."
msgstr ""

#: glance/api/v1/images.py:949
#, python-format
msgid "Failed to find image to update: %(e)s"
msgstr ""

#: glance/api/v1/images.py:956
#, python-format
msgid "Forbidden to update image: %(e)s"
msgstr ""

#: glance/api/v1/images.py:1047
#, python-format
msgid "Forbidden to delete image: %(e)s"
msgstr ""

#: glance/api/v1/images.py:1109 glance/api/v1/upload_utils.py:203
#, python-format
msgid "Denying attempt to upload image larger than %d bytes."
msgstr ""

#: glance/api/v1/members.py:40 glance/registry/api/v1/members.py:32
msgid "No authenticated user"
msgstr ""

#: glance/api/v1/members.py:52
#, python-format
msgid "Image with identifier %s has been deleted."
msgstr ""

#: glance/api/v1/members.py:116 glance/common/exception.py:295
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image members for "
"this image. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/api/v1/upload_utils.py:72
#, python-format
msgid "Unable to kill image %(id)s: "
msgstr ""

#: glance/api/v1/upload_utils.py:108
#, python-format
msgid "Cleaning up %s after exceeding the quota"
msgstr ""

#: glance/api/v1/upload_utils.py:116
#, python-format
msgid ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded "
"image (%(actual)s) did not match. Setting image status to 'killed'."
msgstr ""

#: glance/api/v1/upload_utils.py:149
#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted"
" during the upload."
msgstr ""

#: glance/api/v1/upload_utils.py:213 glance/api/v2/images.py:133
#, python-format
msgid "Denying attempt to upload image because it exceeds the .quota: %s"
msgstr ""

#: glance/api/v1/upload_utils.py:227
#, python-format
msgid "Received HTTP error while uploading image %s"
msgstr ""

#: glance/api/v1/upload_utils.py:242
#, python-format
msgid "Failed to upload image %s"
msgstr ""

#: glance/api/v2/image_data.py:57
#, python-format
msgid "Unable to restore image %(image_id)s: %(e)s"
msgstr ""

#: glance/api/v2/image_data.py:73
#, python-format
msgid ""
"Image %(id)s could not be found after upload.The image may have been "
"deleted during the upload: %(error)s Cleaning up the chunks uploaded"
msgstr ""

#: glance/api/v2/image_data.py:118
#, python-format
msgid "Image exceeds the storage quota: %s"
msgstr ""

#: glance/api/v2/image_data.py:125
#, python-format
msgid "The incoming image is too large: %s"
msgstr ""

#: glance/api/v2/image_data.py:140
msgid "Failed to upload image data due to HTTP error"
msgstr ""

#: glance/api/v2/image_data.py:145
msgid "Failed to upload image data due to internal error"
msgstr ""

#: glance/api/v2/image_members.py:191 glance/api/v2/images.py:291
msgid "Body expected in request."
msgstr ""

#: glance/api/v2/image_members.py:202
msgid "Member to be added not specified"
msgstr ""

#: glance/api/v2/image_members.py:205
msgid "Member can't be empty"
msgstr ""

#: glance/api/v2/image_members.py:214
msgid "Status not specified"
msgstr ""

#: glance/api/v2/image_members.py:269
msgid "An identifier for the image member (tenantId)"
msgstr ""

#: glance/api/v2/image_members.py:273 glance/api/v2/images.py:650
msgid "An identifier for the image"
msgstr ""

#: glance/api/v2/image_members.py:279
msgid "Date and time of image member creation"
msgstr ""

#: glance/api/v2/image_members.py:286
msgid "Date and time of last modification of image member"
msgstr ""

#: glance/api/v2/image_members.py:291
msgid "The status of this image member"
msgstr ""

#: glance/api/v2/images.py:157 glance/api/v2/images.py:185
#, python-format
msgid "Property %s does not exist."
msgstr ""

#: glance/api/v2/images.py:169
#, python-format
msgid "Property %s already present."
msgstr ""

#: glance/api/v2/images.py:180
#, python-format
msgid "Property %s may not be removed."
msgstr ""

#: glance/api/v2/images.py:198
#, python-format
msgid "Failed to find image %(image_id)s to delete"
msgstr ""

#: glance/api/v2/images.py:217
msgid "Cannot replace locations from a non-empty list to a non-empty list."
msgstr ""

#: glance/api/v2/images.py:241
msgid "Invalid position for adding a location."
msgstr ""

#: glance/api/v2/images.py:257
msgid "Invalid position for removing a location."
msgstr ""

#: glance/api/v2/images.py:299 glance/api/v2/images.py:399
#, python-format
msgid "Attribute '%s' is read-only."
msgstr ""

#: glance/api/v2/images.py:324 glance/api/v2/images.py:346
#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr ""

#: glance/api/v2/images.py:332
msgid ""
"Operation objects must contain only one member named \"add\", \"remove\","
" or \"replace\"."
msgstr ""

#: glance/api/v2/images.py:337
msgid ""
"Operation objects must contain exactly one member named \"add\", "
"\"remove\", or \"replace\"."
msgstr ""

#: glance/api/v2/images.py:374
#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr ""

#: glance/api/v2/images.py:377
#, python-format
msgid "Pointer `%s` contains adjacent \"/\"."
msgstr ""

#: glance/api/v2/images.py:380
#, python-format
msgid "Pointer `%s` end with \"/\"."
msgstr ""

#: glance/api/v2/images.py:383
#, python-format
msgid "Pointer `%s` does not contains valid token."
msgstr ""

#: glance/api/v2/images.py:386
#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr ""

#: glance/api/v2/images.py:392
#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr ""

#: glance/api/v2/images.py:402
#, python-format
msgid "Attribute '%s' is reserved."
msgstr ""

#: glance/api/v2/images.py:432
#, python-format
msgid "Invalid JSON pointer for this resource: '/%s'"
msgstr ""

#: glance/api/v2/images.py:444
msgid "Unrecognized JSON Schema draft version"
msgstr ""

#: glance/api/v2/images.py:465
msgid "Request body must be a JSON array of operation objects."
msgstr ""

#: glance/api/v2/images.py:470
msgid "Operations must be JSON objects."
msgstr ""

#: glance/api/v2/images.py:492 glance/api/v2/tasks.py:166
#: glance/registry/api/v1/images.py:247
msgid "limit param must be an integer"
msgstr ""

#: glance/api/v2/images.py:496 glance/api/v2/tasks.py:170
#: glance/registry/api/v1/images.py:250
msgid "limit param must be positive"
msgstr ""

#: glance/api/v2/images.py:503 glance/api/v2/tasks.py:136
#, python-format
msgid "Invalid sort direction: %s"
msgstr ""

#: glance/api/v2/images.py:510
#, python-format
msgid "Invalid status: %s"
msgstr ""

#: glance/api/v2/images.py:519
#, python-format
msgid "Invalid visibility value: %s"
msgstr ""

#: glance/api/v2/images.py:656
msgid "Descriptive name for the image"
msgstr ""

#: glance/api/v2/images.py:661
msgid "Status of the image (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:667
msgid "Scope of image accessibility"
msgstr ""

#: glance/api/v2/images.py:672
msgid "If true, image will not be deletable."
msgstr ""

#: glance/api/v2/images.py:676
msgid "md5 hash of image contents. (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:681
msgid "Owner of the image"
msgstr ""

#: glance/api/v2/images.py:686
msgid "Size of image file in bytes (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:690
msgid "Virtual size of image in bytes (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:694
msgid "Format of the container"
msgstr ""

#: glance/api/v2/images.py:699
msgid "Format of the disk"
msgstr ""

#: glance/api/v2/images.py:704
msgid "Date and time of image registration (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:712
msgid "Date and time of the last image modification (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:718
msgid "List of strings related to the image"
msgstr ""

#: glance/api/v2/images.py:726
msgid "URL to access the image file kept in external store (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:731
msgid "Amount of ram (in MB) required to boot image."
msgstr ""

#: glance/api/v2/images.py:735
msgid "Amount of disk space (in GB) required to boot image."
msgstr ""

#: glance/api/v2/images.py:765
msgid "A set of URLs to access the image file kept in external store"
msgstr ""

#: glance/api/v2/images.py:804
#, python-format
msgid ""
"Could not find schema properties file %s. Continuing without custom "
"properties"
msgstr ""

#: glance/api/v2/tasks.py:66
#, python-format
msgid "Forbidden to create task. Reason: %(reason)s"
msgstr ""

#: glance/api/v2/tasks.py:104
#, python-format
msgid "Failed to find task %(task_id)s. Reason: %(reason)s"
msgstr ""

#: glance/api/v2/tasks.py:109
#, python-format
msgid "Forbidden to get task %(task_id)s. Reason: %(reason)s"
msgstr ""

#: glance/api/v2/tasks.py:116
msgid ""
"This operation is currently not permitted on Glance Tasks. They are auto "
"deleted after reaching the time based on their expires_at property."
msgstr ""

#: glance/api/v2/tasks.py:130
msgid "Body expected in request"
msgstr ""

#: glance/api/v2/tasks.py:145
#, python-format
msgid "Invalid status value: %s"
msgstr ""

#: glance/api/v2/tasks.py:151
#, python-format
msgid "Invalid type value: %s"
msgstr ""

#: glance/api/v2/tasks.py:158 glance/registry/api/v1/images.py:259
msgid "Invalid marker format"
msgstr ""

#: glance/api/v2/tasks.py:179
#, python-format
msgid "Task '%s' is required"
msgstr ""

#: glance/api/v2/tasks.py:302
msgid "An identifier for the task"
msgstr ""

#: glance/api/v2/tasks.py:303
msgid ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0"
"-9a-fA-F]){12}$"
msgstr ""

#: glance/api/v2/tasks.py:308
msgid "The type of task represented by this content"
msgstr ""

#: glance/api/v2/tasks.py:315
msgid "The current status of this task"
msgstr ""

#: glance/api/v2/tasks.py:325
msgid "The parameters required by task, JSON blob"
msgstr ""

#: glance/api/v2/tasks.py:329
msgid "The result of current task, JSON blob"
msgstr ""

#: glance/api/v2/tasks.py:333
msgid "An identifier for the owner of this task"
msgstr ""

#: glance/api/v2/tasks.py:337
msgid ""
"Human-readable informative message only included when appropriate "
"(usually on failure)"
msgstr ""

#: glance/api/v2/tasks.py:342
msgid "Datetime when this resource would be subject to removal"
msgstr ""

#: glance/api/v2/tasks.py:347
msgid "Datetime when this resource was created"
msgstr ""

#: glance/api/v2/tasks.py:351
msgid "Datetime when this resource was updated"
msgstr ""

#: glance/cmd/control.py:102
#, python-format
msgid "%(serv)s appears to already be running: %(pid)s"
msgstr ""

#: glance/cmd/control.py:106
#, python-format
msgid "Removing stale pid file %s"
msgstr ""

#: glance/cmd/control.py:115
msgid "Unable to increase file descriptor limit.  Running as non-root?"
msgstr ""

#: glance/cmd/control.py:160
#, python-format
msgid "%(verb)sing %(serv)s"
msgstr ""

#: glance/cmd/control.py:175
#, python-format
msgid "unable to launch %(serv)s. Got error: %(e)s"
msgstr ""

#: glance/cmd/control.py:206
#, python-format
msgid "%(serv)s (pid %(pid)s) is running..."
msgstr ""

#: glance/cmd/control.py:209
#, python-format
msgid "%s is stopped"
msgstr ""

#: glance/cmd/control.py:225
#, python-format
msgid ""
"Unable to create pid file %(pid)s.  Running as non-root?\n"
"Falling back to a temp file, you can stop %(service)s service using:\n"
"  %(file)s %(server)s stop --pid-file %(fb)s"
msgstr ""

#: glance/cmd/control.py:255
#, python-format
msgid "Stopping %(serv)s (pid %(pid)s) with signal(%(sig)s)"
msgstr ""

#: glance/cmd/control.py:259
#, python-format
msgid "Process %d not running"
msgstr ""

#: glance/cmd/control.py:266
#, python-format
msgid "Waited 15 seconds for pid %(pid)s (%(file)s) to die; giving up"
msgstr ""

#: glance/cmd/control.py:269
#, python-format
msgid "%s is already stopped"
msgstr ""

#: glance/cmd/control.py:346
#, python-format
msgid "Suppressed respawn as %(serv)s was %(rsn)s."
msgstr ""

#: glance/cmd/manage.py:57
msgid ""
"DEPRECATED. TO BE REMOVED IN THE JUNO RELEASE. Whether or not to enforce "
"that all DB tables have charset utf8. If your database tables do not have"
" charset utf8 you will need to convert before this option is removed. "
"This option is only relevant if your database engine is MySQL."
msgstr ""

#: glance/cmd/manage.py:86
msgid ""
"Warning: The db_enforce_mysql_charset option is now deprecated and will "
"be removed in the Juno release. Please migrate DB manually e.g. convert "
"data of all tables to UTF-8 charset."
msgstr ""

#: glance/cmd/replicator.py:55
#, python-format
msgid ""
"The image %s is already present on the slave, but our check for it did "
"not find it. This indicates that we do not have permissions to see all "
"the images on the slave server."
msgstr ""

#: glance/cmd/replicator.py:280 glance/cmd/replicator.py:312
#: glance/cmd/replicator.py:383 glance/cmd/replicator.py:457
#: glance/cmd/replicator.py:527
msgid "Too few arguments."
msgstr ""

#: glance/cmd/replicator.py:296
#, python-format
msgid "Total size is %(size)d bytes across %(img_count)d images"
msgstr ""

#: glance/cmd/replicator.py:321 glance/cmd/replicator.py:397
#, python-format
msgid "Considering: %s"
msgstr ""

#: glance/cmd/replicator.py:325
msgid "... storing"
msgstr ""

#: glance/cmd/replicator.py:336
msgid "... image is active"
msgstr ""

#: glance/cmd/replicator.py:423 glance/cmd/replicator.py:496
msgid "... metadata has changed"
msgstr ""

#: glance/cmd/replicator.py:430
msgid "... dump is missing image data, skipping"
msgstr ""

#: glance/cmd/replicator.py:472
#, python-format
msgid "Considering %(id)s"
msgstr ""

#: glance/cmd/replicator.py:502
#, python-format
msgid "%s is being synced"
msgstr ""

#: glance/cmd/replicator.py:556
#, python-format
msgid ""
"%(image_id)s: field %(key)s differs (source is %(master_value)s, "
"destination is %(slave_value)s)"
msgstr ""

#: glance/cmd/replicator.py:570
#, python-format
msgid "%s: entirely missing from the destination"
msgstr ""

#: glance/cmd/replicator.py:677
#, python-format
msgid "Unknown command: %s"
msgstr ""

#: glance/common/auth.py:186 glance/common/auth.py:226
#, python-format
msgid "Unexpected response: %s"
msgstr ""

#: glance/common/auth.py:254
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr ""

#: glance/common/auth.py:275
#, python-format
msgid "Encountered service with no \"type\": %s"
msgstr ""

#: glance/common/client.py:240
msgid ""
"You have selected to use SSL in connecting, and you have supplied a cert,"
" however you have failed to supply either a key_file parameter or set the"
" GLANCE_CLIENT_KEY_FILE environ variable"
msgstr ""

#: glance/common/client.py:248
msgid ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the"
" GLANCE_CLIENT_CERT_FILE environ variable"
msgstr ""

#: glance/common/client.py:257
#, python-format
msgid "The key file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:264
#, python-format
msgid "The cert file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:271
#, python-format
msgid "The CA file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:410
#, python-format
msgid "Constructed URL: %s"
msgstr ""

#: glance/common/config.py:34
msgid ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:glance-api-keystone] use the value \"keystone\""
msgstr ""

#: glance/common/config.py:40
msgid "Name of the paste configuration file."
msgstr ""

#: glance/common/config.py:45
msgid "Supported values for the 'container_format' image attribute"
msgstr ""

#: glance/common/config.py:52
msgid "Supported values for the 'disk_format' image attribute"
msgstr ""

#: glance/common/config.py:60
msgid "Time in hours for which a task lives after, either succeeding or failing"
msgstr ""

#: glance/common/config.py:67
msgid ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"
msgstr ""

#: glance/common/config.py:70
msgid ""
"Maximum number of image members per image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance/common/config.py:73
msgid ""
"Maximum number of properties allowed on an image. Negative values "
"evaluate to unlimited."
msgstr ""

#: glance/common/config.py:76
msgid ""
"Maximum number of tags allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance/common/config.py:79
msgid ""
"Maximum number of locations allowed on an image. Negative values evaluate"
" to unlimited."
msgstr ""

#: glance/common/config.py:82
msgid "Python module path of data access API"
msgstr ""

#: glance/common/config.py:84
msgid ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"
msgstr ""

#: glance/common/config.py:87
msgid "Maximum permissible number of items that could be returned by a request"
msgstr ""

#: glance/common/config.py:90
msgid ""
"Whether to include the backend image storage location in image "
"properties. Revealing storage location can be a security risk, so use "
"this setting with caution!"
msgstr ""

#: glance/common/config.py:95
msgid ""
"Whether to include the backend image locations in image properties. "
"Revealing storage location can be a security risk, so use this setting "
"with caution!  The overrides show_image_direct_url."
msgstr ""

#: glance/common/config.py:100
msgid ""
"Maximum size of image a user can upload in bytes. Defaults to "
"1099511627776 bytes (1 TB)."
msgstr ""

#: glance/common/config.py:103
msgid ""
"Set a system wide quota for every user. This value is the total capacity "
"that a user can use across all storage systems. A value of 0 means "
"unlimited.Optional unit can be specified for the value. Accepted units "
"are B, KB, MB, GB and TB representing Bytes, KiloBytes, MegaBytes, "
"GigaBytes and TeraBytesrespectively. If no unit is specified then Bytes "
"is assumed. Note that there should not be any space between value and "
"unit and units are case sensitive."
msgstr ""

#: glance/common/config.py:113
msgid "Deploy the v1 OpenStack Images API."
msgstr ""

#: glance/common/config.py:115
msgid "Deploy the v2 OpenStack Images API."
msgstr ""

#: glance/common/config.py:117
msgid "Deploy the v1 OpenStack Registry API."
msgstr ""

#: glance/common/config.py:119
msgid "Deploy the v2 OpenStack Registry API."
msgstr ""

#: glance/common/config.py:121
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr ""

#: glance/common/config.py:124
msgid "The port on which a pydev process is listening for connections."
msgstr ""

#: glance/common/config.py:127
msgid ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."
msgstr ""

#: glance/common/config.py:185
#, python-format
msgid "Unable to locate paste config file for %s."
msgstr ""

#: glance/common/config.py:224
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""

#: glance/common/exception.py:38
msgid "An unknown exception occurred"
msgstr ""

#: glance/common/exception.py:63
#, python-format
msgid "Missing required credential: %(required)s"
msgstr ""

#: glance/common/exception.py:67
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""

#: glance/common/exception.py:72
msgid "An object with the specified identifier was not found."
msgstr ""

#: glance/common/exception.py:76
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr ""

#: glance/common/exception.py:80
msgid "The Store URI was malformed."
msgstr ""

#: glance/common/exception.py:84
msgid "An object with the same identifier already exists."
msgstr ""

#: glance/common/exception.py:88
msgid "An object with the same identifier is currently being operated on."
msgstr ""

#: glance/common/exception.py:93
msgid "There is not enough disk space on the image storage media."
msgstr ""

#: glance/common/exception.py:97
#, python-format
msgid ""
"The size of the data %(image_size)s will exceed the limit. %(remaining)s "
"bytes remaining."
msgstr ""

#: glance/common/exception.py:102
msgid "Permission to write image storage media denied."
msgstr ""

#: glance/common/exception.py:106
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""

#: glance/common/exception.py:110
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr ""

#: glance/common/exception.py:114
msgid "Authorization failed."
msgstr ""

#: glance/common/exception.py:118
msgid "You are not authenticated."
msgstr ""

#: glance/common/exception.py:122 glance/common/exception.py:126
msgid "You are not authorized to complete this action."
msgstr ""

#: glance/common/exception.py:130
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr ""

#: glance/common/exception.py:134
msgid "Data supplied was not valid."
msgstr ""

#: glance/common/exception.py:138
#: glance/openstack/common/db/sqlalchemy/utils.py:58
msgid "Sort key supplied was not valid."
msgstr ""

#: glance/common/exception.py:142
msgid "Invalid configuration in property protection file."
msgstr ""

#: glance/common/exception.py:146
msgid "Invalid configuration in glance-swift conf file."
msgstr ""

#: glance/common/exception.py:150
msgid "Unable to filter using the specified range."
msgstr ""

#: glance/common/exception.py:154
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr ""

#: glance/common/exception.py:158
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr ""

#: glance/common/exception.py:162
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr ""

#: glance/common/exception.py:166
msgid "There was an error connecting to a server"
msgstr ""

#: glance/common/exception.py:170
msgid "There was an error configuring the client."
msgstr ""

#: glance/common/exception.py:174
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:180
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:191
msgid ""
"The request returned 503 Service Unavilable. This generally occurs on "
"service overload or other transient outage."
msgstr ""

#: glance/common/exception.py:202
msgid "The request returned 500 Internal Server Error."
msgstr ""

#: glance/common/exception.py:206
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:211
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr ""

#: glance/common/exception.py:215
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr ""

#: glance/common/exception.py:220
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""

#: glance/common/exception.py:225
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""

#: glance/common/exception.py:230
msgid "Deleting images from this store is not supported."
msgstr ""

#: glance/common/exception.py:234
msgid "Getting images from this store is not supported."
msgstr ""

#: glance/common/exception.py:238
msgid "Adding images to this store is not supported."
msgstr ""

#: glance/common/exception.py:242
msgid "Configuration for store failed. Adding images to this store is disabled."
msgstr ""

#: glance/common/exception.py:247
msgid "Store is not configured."
msgstr ""

#: glance/common/exception.py:251
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""

#: glance/common/exception.py:255
msgid "Received invalid HTTP redirect."
msgstr ""

#: glance/common/exception.py:259
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr ""

#: glance/common/exception.py:263
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""

#: glance/common/exception.py:269
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr ""

#: glance/common/exception.py:273
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr ""

#: glance/common/exception.py:277
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr ""

#: glance/common/exception.py:282
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr ""

#: glance/common/exception.py:286
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Glance."
msgstr ""

#: glance/common/exception.py:291
msgid "The provided image is too large."
msgstr ""

#: glance/common/exception.py:301
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:306
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image tags. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:311
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image locations. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:316
#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr ""

#: glance/common/exception.py:320
msgid "An unknown task exception occurred"
msgstr ""

#: glance/common/exception.py:324
#, python-format
msgid "Task with the given id %(task_id)s was not found"
msgstr ""

#: glance/common/exception.py:328
#, python-format
msgid "Provided status of task is unsupported: %(status)s"
msgstr ""

#: glance/common/exception.py:332
#, python-format
msgid "Provided type of task is unsupported: %(type)s"
msgstr ""

#: glance/common/exception.py:336
#, python-format
msgid "Status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr ""

#: glance/common/exception.py:341
#, python-format
msgid "The location %(location)s already exists"
msgstr ""

#: glance/common/exception.py:349
#, python-format
msgid "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"
msgstr ""

#: glance/common/exception.py:354
#, python-format
msgid ""
"Image status transition from %(cur_status)s to %(new_status)s is not "
"allowed"
msgstr ""

#: glance/common/property_utils.py:36
msgid "The location of the property protection file."
msgstr ""

#: glance/common/property_utils.py:39
msgid ""
"This config value indicates whether \"roles\" or \"policies\" are used in"
" the property protection file."
msgstr ""

#: glance/common/property_utils.py:74
#, python-format
msgid "Couldn't find property protection file %(file)s: %(error)s."
msgstr ""

#: glance/common/property_utils.py:81
#, python-format
msgid ""
"Invalid value '%s' for 'property_protection_rule_format'. The permitted "
"values are 'roles' and 'policies'"
msgstr ""

#: glance/common/property_utils.py:100
#, python-format
msgid ""
"Multiple policies '%s' not allowedfor a given operation. Policies can be "
"combined in the policy file"
msgstr ""

#: glance/common/property_utils.py:113
#, python-format
msgid ""
"Malformed property protection rule in [%(prop)s] %(op)s=%(perm)s: '@' and"
" '!' are mutually exclusive"
msgstr ""

#: glance/common/property_utils.py:126
#, python-format
msgid ""
"Property protection on operation %(operation)s for rule %(rule)s is not "
"found. No role will be allowed to perform this operation."
msgstr ""

#: glance/common/property_utils.py:138
#, python-format
msgid "Encountered a malformed property protection rule %(rule)s: %(error)s."
msgstr ""

#: glance/common/rpc.py:140
msgid "Request must be a list of commands"
msgstr ""

#: glance/common/rpc.py:145
#, python-format
msgid "Bad Command: %s"
msgstr ""

#: glance/common/rpc.py:152
#, python-format
msgid "Wrong command structure: %s"
msgstr ""

#: glance/common/rpc.py:161
msgid "Command not found"
msgstr ""

#: glance/common/rpc.py:183
#, python-format
msgid ""
"RPC Call Error: %(val)s\n"
"%(tb)s"
msgstr ""

#: glance/common/swift_store_utils.py:29
msgid ""
"The reference to the default swift account/backing store parameters to "
"use for adding new images."
msgstr ""

#: glance/common/swift_store_utils.py:32
msgid ""
"The address where the Swift authentication service is "
"listening.(deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:35
msgid ""
"The user to authenticate against the Swift authentication service "
"(deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:38
msgid ""
"Auth key for the user authenticating against the Swift authentication "
"service. (deprecated)"
msgstr ""

#: glance/common/swift_store_utils.py:41
msgid "The config file that has the swift account(s)configs."
msgstr ""

#: glance/common/swift_store_utils.py:83
#, python-format
msgid "swift config file %(conf_file)s:%(exc)s not found"
msgstr ""

#: glance/common/swift_store_utils.py:97
msgid "Invalid format of swift store configcfg"
msgstr ""

#: glance/common/utils.py:111
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr ""

#: glance/common/utils.py:258
#, python-format
msgid "Bad header: %(header_name)s"
msgstr ""

#: glance/common/utils.py:268
#, python-format
msgid "Cannot convert image %(key)s '%(value)s' to an integer."
msgstr ""

#: glance/common/utils.py:275
#, python-format
msgid "Image %(key)s must be >= 0 ('%(value)s' specified)."
msgstr ""

#: glance/common/utils.py:448
msgid ""
"Error setting up the debug environment.  Verify that the option "
"pydev_worker_debug_host is pointing to a valid hostname or IP on which a "
"pydev server is listening on the port indicated by "
"pydev_worker_debug_port."
msgstr ""

#: glance/common/utils.py:485
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: glance/common/utils.py:518
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  "
"Please verify it.  Error: %(ioe)s"
msgstr ""

#: glance/common/utils.py:525
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  "
"Please verify it. OpenSSL error: %(ce)s"
msgstr ""

#: glance/common/utils.py:539
#, python-format
msgid ""
"There is a problem with your key pair.  Please verify that cert "
"%(cert_file)s and key %(key_file)s belong together.  OpenSSL error %(ce)s"
msgstr ""

#: glance/common/utils.py:617
#, python-format
msgid "Host and port \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:620
#, python-format
msgid "Port \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:629
#, python-format
msgid "Host \"%s\" is not valid."
msgstr ""

#: glance/common/utils.py:632
#, python-format
msgid ""
"%s Please specify a host:port pair, where host is an IPv4 address, IPv6 "
"address, hostname, or FQDN. If using an IPv6 address, enclose it in "
"brackets separately from the port (i.e., \"[fe80::a:b:c]:9876\")."
msgstr ""

#: glance/common/wsgi.py:55
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr ""

#: glance/common/wsgi.py:58
msgid "The port on which the server will listen."
msgstr ""

#: glance/common/wsgi.py:63
msgid "The backlog value that will be used when creating the TCP listener socket."
msgstr ""

#: glance/common/wsgi.py:66
msgid ""
"The value for the socket option TCP_KEEPIDLE.  This is the time in "
"seconds that the connection must be idle before TCP starts sending "
"keepalive probes."
msgstr ""

#: glance/common/wsgi.py:69
msgid "CA certificate file to use to verify connecting clients."
msgstr ""

#: glance/common/wsgi.py:71
msgid "Certificate file to use when starting API server securely."
msgstr ""

#: glance/common/wsgi.py:73
msgid "Private key file to use when starting API server securely."
msgstr ""

#: glance/common/wsgi.py:79
msgid ""
"The number of child process workers that will be created to service "
"requests. The default will be equal to the number of CPUs available."
msgstr ""

#: glance/common/wsgi.py:83
msgid ""
"Name of eventlet hub to use. Traditionally, we have only supported "
"'poll', however 'selects' may be appropriate for some platforms. See "
"http://eventlet.net/doc/hubs.html for more details."
msgstr ""

#: glance/common/wsgi.py:88
msgid ""
"Maximum line size of message headers to be accepted. max_header_line may "
"need to be increased when using large tokens (typically those generated "
"by the Keystone v3 API with big service catalogs"
msgstr ""

#: glance/common/wsgi.py:134
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: glance/common/wsgi.py:172
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: glance/common/wsgi.py:247
#, python-format
msgid "Starting %d workers"
msgstr ""

#: glance/common/wsgi.py:262
#, python-format
msgid "Removing dead child %s"
msgstr ""

#: glance/common/wsgi.py:265
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr ""

#: glance/common/wsgi.py:269
msgid "All workers have terminated. Exiting"
msgstr ""

#: glance/common/wsgi.py:277
msgid "Caught keyboard interrupt. Exiting."
msgstr ""

#: glance/common/wsgi.py:303
#, python-format
msgid "Child %d exiting normally"
msgstr ""

#: glance/common/wsgi.py:308
#, python-format
msgid "Started child %s"
msgstr ""

#: glance/common/wsgi.py:321
#, python-format
msgid "eventlet '%s' hub is not available on this platform"
msgstr ""

#: glance/common/wsgi.py:338
msgid "Starting single process server"
msgstr ""

#: glance/common/wsgi.py:555
msgid "Malformed JSON in request body."
msgstr ""

#: glance/common/location_strategy/__init__.py:25
msgid ""
"This value sets what strategy will be used to determine the image "
"location order. Currently two strategies are packaged with Glance "
"'location_order' and 'store_type'."
msgstr ""

#: glance/common/location_strategy/__init__.py:52
#, python-format
msgid ""
"%(strategy)s is registered as a module twice. %(module)s is not being "
"used."
msgstr ""

#: glance/common/location_strategy/__init__.py:61
#, python-format
msgid "Failed to load location strategy module %(module)s: %(e)s"
msgstr ""

#: glance/common/location_strategy/__init__.py:74
#, python-format
msgid ""
"Invalid location_strategy option: %(name)s. The valid strategy option(s) "
"is(are): %(strategies)s"
msgstr ""

#: glance/common/location_strategy/store_type.py:25
msgid ""
"The store names to use to get store preference order. The name must be "
"registered by one of the stores defined by the 'known_stores' config "
"option. This option will be applied when you using 'store_type' option as"
" image location strategy defined by the 'location_strategy' config "
"option."
msgstr ""

#: glance/db/__init__.py:67 glance/db/__init__.py:170 glance/db/__init__.py:182
#, python-format
msgid "No image found with ID %s"
msgstr ""

#: glance/db/__init__.py:241
#, python-format
msgid ""
"The target member %(member_id)s is already associated with image "
"%(image_id)s."
msgstr ""

#: glance/db/__init__.py:258
#, python-format
msgid "The specified member %s could not be found"
msgstr ""

#: glance/db/__init__.py:336 glance/db/__init__.py:357
#: glance/db/__init__.py:374 glance/db/simple/api.py:764
#, python-format
msgid "Could not find task %s"
msgstr ""

#: glance/db/simple/api.py:43
#, python-format
msgid "Calling %(funcname)s: args=%(args)s, kwargs=%(kwargs)s"
msgstr ""

#: glance/db/simple/api.py:48
#, python-format
msgid "Returning %(funcname)s: %(output)s"
msgstr ""

#: glance/db/simple/api.py:258 glance/db/sqlalchemy/api.py:408
msgid "Unable to filter on a range with a non-numeric value."
msgstr ""

#: glance/db/simple/api.py:331
#, python-format
msgid "Could not find image %s"
msgstr ""

#: glance/db/simple/api.py:335
msgid "Unable to get deleted image"
msgstr ""

#: glance/db/simple/api.py:339
msgid "Unable to get unowned image"
msgstr ""

#: glance/db/simple/api.py:427 glance/db/sqlalchemy/api.py:952
msgid "Image id is required."
msgstr ""

#: glance/db/simple/api.py:769
#, python-format
msgid "Unable to get deleted task %s"
msgstr ""

#: glance/db/simple/api.py:892
msgid "Task does not exist"
msgstr ""

#: glance/db/simple/api.py:930
#, python-format
msgid "Could not find task info %s"
msgstr ""

#: glance/db/sqlalchemy/api.py:85
msgid "Attempted to modify image user did not own."
msgstr ""

#: glance/db/sqlalchemy/api.py:86
msgid "You do not own this image"
msgstr ""

#: glance/db/sqlalchemy/api.py:275
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: glance/db/sqlalchemy/api.py:338
#: glance/openstack/common/db/sqlalchemy/utils.py:119
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: glance/db/sqlalchemy/api.py:683
#: glance/tests/unit/v2/test_registry_client.py:500
#, python-format
msgid ""
"cannot transition from %(current)s to %(next)s in update (wanted "
"from_state=%(from)s)"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/schema.py:96
#, python-format
msgid "creating table %(table)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/schema.py:102
#, python-format
msgid "dropping table %(table)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:60
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:90
#, python-format
msgid "Invalid store uri for image: %(image_id)s. Details: %(reason)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:88
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:151
msgid ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:125
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:187
#, python-format
msgid "Badly formed credentials '%(creds)s' in Swift URI"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:137
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:199
#: glance/store/swift.py:248
msgid "Badly formed credentials in Swift URI."
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:154
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:216
#, python-format
msgid "Badly formed S3 URI: %(uri)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:66
msgid ""
"'metadata_encryption_key' was not specified in the config file or a "
"config file was not specified. This means that this migration is a NOOP."
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:86
#, python-format
msgid "Failed to decrypt location value for image %(image_id)s"
msgstr ""

#: glance/domain/__init__.py:60
#, python-format
msgid "new_image() got unexpected keywords %s"
msgstr ""

#: glance/domain/__init__.py:130
#, python-format
msgid "__init__() got unexpected keyword argument '%s'"
msgstr ""

#: glance/domain/__init__.py:152
#, python-format
msgid "Property %s must be set prior to saving data."
msgstr ""

#: glance/domain/__init__.py:155
#, python-format
msgid "Properties %s must be set prior to saving data."
msgstr ""

#: glance/domain/__init__.py:172
msgid "Visibility must be either \"public\" or \"private\""
msgstr ""

#: glance/domain/__init__.py:191
msgid "Attribute container_format can be only replaced for a queued image."
msgstr ""

#: glance/domain/__init__.py:203
msgid "Attribute disk_format can be only replaced for a queued image."
msgstr ""

#: glance/domain/__init__.py:215 glance/domain/__init__.py:228
msgid "Cannot be a negative value"
msgstr ""

#: glance/domain/__init__.py:293
msgid "Status must be \"pending\", \"accepted\" or \"rejected\"."
msgstr ""

#: glance/domain/__init__.py:369
#, python-format
msgid "Task status changed from %(cur_status)s to %(new_status)s"
msgstr ""

#: glance/domain/__init__.py:374
#, python-format
msgid "Task status failed to change from %(cur_status)s to %(new_status)s"
msgstr ""

#: glance/image_cache/__init__.py:35
msgid "The driver to use for image cache management."
msgstr ""

#: glance/image_cache/__init__.py:37
msgid "The maximum size in bytes that the cache can use."
msgstr ""

#: glance/image_cache/__init__.py:39
msgid ""
"The amount of time to let an image remain in the cache without being "
"accessed."
msgstr ""

#: glance/image_cache/__init__.py:42
msgid "Base directory that the Image Cache uses."
msgstr ""

#: glance/image_cache/__init__.py:64
#, python-format
msgid "Image cache loaded driver '%s'."
msgstr ""

#: glance/image_cache/__init__.py:67
#, python-format
msgid ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."
msgstr ""

#: glance/image_cache/__init__.py:74 glance/image_cache/__init__.py:93
msgid "Defaulting to SQLite driver."
msgstr ""

#: glance/image_cache/__init__.py:88
#, python-format
msgid ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"
msgstr ""

#: glance/image_cache/__init__.py:254
#, python-format
msgid "Checksum verification failed. Aborted caching of image '%s'."
msgstr ""

#: glance/image_cache/__init__.py:264
#, python-format
msgid ""
"Exception encountered while tee'ing image '%(image_id)s' into cache: "
"%(error)s. Continuing with response."
msgstr ""

#: glance/image_cache/client.py:117
msgid ""
"--os_auth_url option or OS_AUTH_URL environment variable required when "
"keystone authentication strategy is enabled\n"
msgstr ""

#: glance/image_cache/prefetcher.py:46
#, python-format
msgid "Image '%s' is not active. Not caching."
msgstr ""

#: glance/image_cache/prefetcher.py:51
#, python-format
msgid "No metadata found for image '%s'"
msgstr ""

#: glance/image_cache/prefetcher.py:78
msgid "Failed to successfully cache all images in queue."
msgstr ""

#: glance/image_cache/prefetcher.py:82
#, python-format
msgid "Successfully cached all %d images"
msgstr ""

#: glance/image_cache/drivers/base.py:54
#, python-format
msgid "Failed to read %s from config"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:40
msgid ""
"The path to the sqlite file database that will be used for image cache "
"management."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:122
#, python-format
msgid "Failed to initialize the image cache database. Got error: %s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:393
#, python-format
msgid "Error executing SQLite call. Got error: %s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:409
#: glance/image_cache/drivers/xattr.py:338
#, python-format
msgid "Not queueing image '%s'. Already cached."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:414
#: glance/image_cache/drivers/xattr.py:343
#, python-format
msgid "Not queueing image '%s'. Already being written to cache"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:420
#: glance/image_cache/drivers/xattr.py:349
#, python-format
msgid "Not queueing image '%s'. Already queued."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:438
#, python-format
msgid "Removed invalid cache file %s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:452
#, python-format
msgid "Removed stalled cache file %s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:454
#, python-format
msgid "Failed to delete file %(path)s. Got error: %(e)s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:491
#: glance/image_cache/drivers/xattr.py:442
#, python-format
msgid "Cached image file '%s' doesn't exist, unable to delete"
msgstr ""

#: glance/image_cache/drivers/xattr.py:105
#, python-format
msgid ""
"The device housing the image cache directory %(image_cache_dir)s does not"
" support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the "
"cache directory."
msgstr ""

#: glance/image_cache/drivers/xattr.py:395
#, python-format
msgid "Reaped %(reaped)s %(entry_type)s cache entries"
msgstr ""

#: glance/openstack/common/gettextutils.py:320
msgid "Message objects do not support addition."
msgstr ""

#: glance/openstack/common/gettextutils.py:330
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: glance/openstack/common/lockutils.py:102
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: glance/openstack/common/log.py:327
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: glance/openstack/common/log.py:436
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: glance/openstack/common/log.py:486
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: glance/openstack/common/log.py:729
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: glance/openstack/common/policy.py:395
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr ""

#: glance/openstack/common/policy.py:405
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: glance/openstack/common/policy.py:680
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr ""

#: glance/openstack/common/processutils.py:59
msgid "Unexpected error while running command."
msgstr ""

#: glance/openstack/common/processutils.py:62
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: glance/openstack/common/processutils.py:144
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: glance/openstack/common/processutils.py:150
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: glance/openstack/common/processutils.py:247
msgid "Environment not supported over SSH"
msgstr ""

#: glance/openstack/common/processutils.py:251
msgid "process_input not supported over SSH"
msgstr ""

#: glance/openstack/common/strutils.py:92
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: glance/openstack/common/strutils.py:197
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: glance/openstack/common/strutils.py:206
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: glance/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/migration.py:190
msgid "version should be an integer"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/migration.py:219
#, python-format
msgid ""
"Tables \"%s\" have non utf8 collation, please make sure all tables are "
"CHARSET=utf8"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/migration.py:243
msgid ""
"The database is not under version control, but has tables. Please stamp "
"the current version of the schema manually."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/test_migrations.py:92
#, python-format
msgid "config_path is %s"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/test_migrations.py:197
#, python-format
msgid "latest version is %s"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:162
#, python-format
msgid ""
"There is no `deleted` column in `%s` table. Project doesn't use soft-"
"deleted feature."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:174
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:181
#, python-format
msgid "There is no `project_id` column in `%s` table."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:243
msgid "model should be a subclass of ModelBase"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:286
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:292
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:400
msgid "Unsupported id columns type"
msgstr ""

#: glance/quota/__init__.py:318
#, python-format
msgid "Cleaning up %s after exceeding the quota."
msgstr ""

#: glance/registry/__init__.py:25
msgid "Address to find the registry server."
msgstr ""

#: glance/registry/__init__.py:27
msgid "Port the registry server is listening on."
msgstr ""

#: glance/registry/api/v1/images.py:106
#, python-format
msgid "Invalid marker. Image %(id)s could not be found."
msgstr ""

#: glance/registry/api/v1/images.py:108 glance/registry/api/v1/images.py:113
msgid "Invalid marker. Image could not be found."
msgstr ""

#: glance/registry/api/v1/images.py:111 glance/registry/api/v1/images.py:329
#: glance/registry/api/v1/images.py:360 glance/registry/api/v1/images.py:479
#: glance/registry/api/v1/members.py:72 glance/registry/api/v1/members.py:106
#: glance/registry/api/v1/members.py:219 glance/registry/api/v1/members.py:279
#, python-format
msgid "Access denied to image %(id)s but returning 'not found'"
msgstr ""

#: glance/registry/api/v1/images.py:116
msgid "Unable to get images"
msgstr ""

#: glance/registry/api/v1/images.py:148
msgid "Returning image list"
msgstr ""

#: glance/registry/api/v1/images.py:166
msgid "Returning detailed image list"
msgstr ""

#: glance/registry/api/v1/images.py:217
msgid "Unrecognized changes-since value"
msgstr ""

#: glance/registry/api/v1/images.py:222
msgid "protected must be True, or False"
msgstr ""

#: glance/registry/api/v1/images.py:269
#, python-format
msgid "Unsupported sort_key. Acceptable values: %s"
msgstr ""

#: glance/registry/api/v1/images.py:278
#, python-format
msgid "Unsupported sort_dir. Acceptable values: %s"
msgstr ""

#: glance/registry/api/v1/images.py:304
msgid "is_public must be None, True, or False"
msgstr ""

#: glance/registry/api/v1/images.py:320
#, python-format
msgid "Successfully retrieved image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:323 glance/registry/api/v1/images.py:364
#: glance/registry/api/v1/images.py:467 glance/registry/api/v1/members.py:66
#: glance/registry/api/v1/members.py:100 glance/registry/api/v1/members.py:213
#: glance/registry/api/v1/members.py:273
#, python-format
msgid "Image %(id)s not found"
msgstr ""

#: glance/registry/api/v1/images.py:333
#, python-format
msgid "Unable to show image %s"
msgstr ""

#: glance/registry/api/v1/images.py:350
#, python-format
msgid "Successfully deleted image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:354
#, python-format
msgid "Delete denied for public image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:368
#, python-format
msgid "Unable to delete image %s"
msgstr ""

#: glance/registry/api/v1/images.py:393
#, python-format
msgid "Rejecting image creation request for invalid image id '%(bad_id)s'"
msgstr ""

#: glance/registry/api/v1/images.py:396
msgid "Invalid image id format"
msgstr ""

#: glance/registry/api/v1/images.py:406
#, python-format
msgid "Successfully created image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:410
#, python-format
msgid "Image with identifier %s already exists!"
msgstr ""

#: glance/registry/api/v1/images.py:414
#, python-format
msgid "Failed to add image metadata. Got error: %(e)s"
msgstr ""

#: glance/registry/api/v1/images.py:419
#, python-format
msgid "Unable to create image %s"
msgstr ""

#: glance/registry/api/v1/images.py:458
#, python-format
msgid "Updating metadata for image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:462
#, python-format
msgid "Failed to update image metadata. Got error: %(e)s"
msgstr ""

#: glance/registry/api/v1/images.py:473
#, python-format
msgid "Update denied for public image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:490
#, python-format
msgid "Unable to update image %s"
msgstr ""

#: glance/registry/api/v1/members.py:77
#, python-format
msgid "Returning member list for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:112 glance/registry/api/v1/members.py:225
#: glance/registry/api/v1/members.py:285
#, python-format
msgid "User lacks permission to share image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:114 glance/registry/api/v1/members.py:227
#: glance/registry/api/v1/members.py:287
msgid "No permission to share that image"
msgstr ""

#: glance/registry/api/v1/members.py:122 glance/registry/api/v1/members.py:138
#: glance/registry/api/v1/members.py:237
#, python-format
msgid "Invalid membership association specified for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:125 glance/registry/api/v1/members.py:141
#: glance/registry/api/v1/members.py:240
#, python-format
msgid "Invalid membership association: %s"
msgstr ""

#: glance/registry/api/v1/members.py:189
#, python-format
msgid "Successfully updated memberships for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:258
#, python-format
msgid "Successfully updated a membership for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:300 glance/registry/api/v1/members.py:317
msgid "Membership could not be found."
msgstr ""

#: glance/registry/api/v1/members.py:304
#, python-format
msgid "Successfully deleted a membership from image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:315
#, python-format
msgid "Member %(id)s not found"
msgstr ""

#: glance/registry/api/v1/members.py:320
#, python-format
msgid "Returning list of images shared with member %(id)s"
msgstr ""

#: glance/registry/api/v2/rpc.py:42
#, python-format
msgid "Registry service can't use %s"
msgstr ""

#: glance/registry/client/__init__.py:20
msgid ""
"The protocol to use for communication with the registry server.  Either "
"http or https."
msgstr ""

#: glance/registry/client/__init__.py:23
msgid "The path to the key file to use in SSL connections to the registry server."
msgstr ""

#: glance/registry/client/__init__.py:26
msgid ""
"The path to the cert file to use in SSL connections to the registry "
"server."
msgstr ""

#: glance/registry/client/__init__.py:29
msgid ""
"The path to the certifying authority cert file to use in SSL connections "
"to the registry server."
msgstr ""

#: glance/registry/client/__init__.py:32
msgid ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority."
msgstr ""

#: glance/registry/client/__init__.py:36
msgid ""
"The period of time, in seconds, that the API server will wait for a "
"registry request to complete. A value of 0 implies no timeout."
msgstr ""

#: glance/registry/client/__init__.py:43 glance/store/__init__.py:53
msgid ""
"Whether to pass through the user token when making requests to the "
"registry."
msgstr ""

#: glance/registry/client/__init__.py:46
msgid "The administrators user name."
msgstr ""

#: glance/registry/client/__init__.py:48
msgid "The administrators password."
msgstr ""

#: glance/registry/client/__init__.py:50
msgid "The tenant name of the administrative user."
msgstr ""

#: glance/registry/client/__init__.py:52
msgid "The URL to the keystone service."
msgstr ""

#: glance/registry/client/__init__.py:54
msgid "The strategy to use for authentication."
msgstr ""

#: glance/registry/client/__init__.py:56
msgid "The region for the authentication service."
msgstr ""

#: glance/registry/client/v1/api.py:33
msgid ""
"Whether to pass through headers containing user and tenant information "
"when making requests to the registry. This allows the registry to use the"
" context middleware without the keystoneclients' auth_token middleware, "
"removing calls to the keystone auth service. It is recommended that when "
"using this option, secure communication between glance api and glance "
"registry is ensured by means other than auth_token middleware."
msgstr ""

#: glance/registry/client/v1/api.py:78 glance/registry/client/v2/api.py:60
msgid "Configuration option was not valid"
msgstr ""

#: glance/registry/client/v1/api.py:82 glance/registry/client/v2/api.py:64
msgid "Could not find required configuration option"
msgstr ""

#: glance/registry/client/v1/client.py:120
#, python-format
msgid "Registry client request %(method)s %(action)s raised %(exc_name)s"
msgstr ""

#: glance/store/__init__.py:38
msgid ""
"List of which store classes and store class locations are currently known"
" to glance at startup."
msgstr ""

#: glance/store/__init__.py:41
msgid ""
"Default scheme to use to store image data. The scheme must be registered "
"by one of the stores defined by the 'known_stores' config option."
msgstr ""

#: glance/store/__init__.py:51
msgid "Turn on/off delayed delete."
msgstr ""

#: glance/store/__init__.py:191
#, python-format
msgid "%s Skipping store driver."
msgstr ""

#: glance/store/__init__.py:197
#, python-format
msgid ""
"%s not found in `known_store`. Stores need to be explicitly enabled in "
"the configuration file."
msgstr ""

#: glance/store/__init__.py:233
#, python-format
msgid "Store for scheme %s not found"
msgstr ""

#: glance/store/__init__.py:326
#, python-format
msgid "Failed to delete image %s in store from URI"
msgstr ""

#: glance/store/__init__.py:332
#, python-format
msgid "Failed to delete image %(image_id)s from store (%(error)s)"
msgstr ""

#: glance/store/__init__.py:367
#, python-format
msgid ""
"The image metadata key %(key)s has an invalid type of %(val)s.  Only "
"dict, list, and unicode are supported."
msgstr ""

#: glance/store/__init__.py:391
#, python-format
msgid ""
"The storage driver %(store)s returned invalid metadata %(metadata)s. This"
" must be a dictionary type"
msgstr ""

#: glance/store/__init__.py:400
#, python-format
msgid ""
"A bad metadata structure was returned from the %(store)s storage driver: "
"%(metadata)s.  %(error)s."
msgstr ""

#: glance/store/base.py:57
#, python-format
msgid "Failed to configure store correctly: %s Disabling add method."
msgstr ""

#: glance/store/cinder.py:115
msgid "URI must start with 'cinder://'"
msgstr ""

#: glance/store/cinder.py:123
msgid "URI contains invalid volume ID"
msgstr ""

#: glance/store/cinder.py:146
msgid "Cinder storage requires a context."
msgstr ""

#: glance/store/cinder.py:150
msgid "Cinder storage requires a service catalog."
msgstr ""

#: glance/store/cinder.py:172
#, python-format
msgid "Failed to get image size due to volume can not be found: %s"
msgstr ""

#: glance/store/cinder.py:177
#, python-format
msgid "Failed to get image size due to internal error: %s"
msgstr ""

#: glance/store/filesystem.py:42
msgid "Directory to which the Filesystem backend store writes images."
msgstr ""

#: glance/store/filesystem.py:45
msgid ""
"List of directories and its priorities to which the Filesystem backend "
"store writes images."
msgstr ""

#: glance/store/filesystem.py:48
msgid ""
"The path to a file which contains the metadata to be returned with any "
"location associated with this store.  The file must contain a valid JSON "
"dict."
msgstr ""

#: glance/store/filesystem.py:79
msgid "No path specified in URI"
msgstr ""

#: glance/store/filesystem.py:132
#, python-format
msgid "Permission to write in %s denied"
msgstr ""

#: glance/store/filesystem.py:149
#, python-format
msgid "Directory to write image files does not exist (%s). Creating."
msgstr ""

#: glance/store/filesystem.py:163
#, python-format
msgid "Unable to create datadir: %s"
msgstr ""

#: glance/store/filesystem.py:177
msgid ""
"Specify at least 'filesystem_store_datadir' or "
"'filesystem_store_datadirs' option"
msgstr ""

#: glance/store/filesystem.py:184
msgid ""
"Specify either 'filesystem_store_datadir' or 'filesystem_store_datadirs' "
"option"
msgstr ""

#: glance/store/filesystem.py:221
#, python-format
msgid ""
"Directory %(datadir_path)s specified multiple times in "
"filesystem_store_datadirs option of filesystem configuration"
msgstr ""

#: glance/store/filesystem.py:246
#, python-format
msgid "Invalid priority value %(priority)s in filesystem configuration"
msgstr ""

#: glance/store/filesystem.py:253
msgid "Invalid directory specified in filesystem configuration"
msgstr ""

#: glance/store/filesystem.py:265
#, python-format
msgid "Image file %s not found"
msgstr ""

#: glance/store/filesystem.py:280
#, python-format
msgid ""
"The JSON in the metadata file %(file)s could not be used: %(error)s  An "
"empty dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:287
#, python-format
msgid ""
"The path for the metadata file %(file)s could not be opened: %(error)s  "
"An empty dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:294
#, python-format
msgid ""
"An error occurred processing the storage systems meta data file: %s.  An "
"empty dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:348
#, python-format
msgid "You cannot delete file %s"
msgstr ""

#: glance/store/filesystem.py:350
#, python-format
msgid "Image file %s does not exist"
msgstr ""

#: glance/store/filesystem.py:395
#, python-format
msgid ""
"There is no enough disk space left on the image storage media. "
"requested=%s"
msgstr ""

#: glance/store/filesystem.py:426
#, python-format
msgid "Image file %s already exists!"
msgstr ""

#: glance/store/filesystem.py:464
#, python-format
msgid "Unable to remove partial image data for image %(id)s: %(error)s"
msgstr ""

#: glance/store/gridfs.py:97
msgid "Missing dependencies: pymongo"
msgstr ""

#: glance/store/gridfs.py:113 glance/store/swift.py:422
#: glance/store/vmware_datastore.py:257
#, python-format
msgid "Could not find %(param)s in configuration options."
msgstr ""

#: glance/store/gridfs.py:180
#, python-format
msgid "GridFS already has an image at location %s"
msgstr ""

#: glance/store/http.py:82
msgid "Credentials are not well-formatted."
msgstr ""

#: glance/store/http.py:88
msgid "No address specified in HTTP URL"
msgstr ""

#: glance/store/http.py:150
msgid "The HTTP URL is invalid."
msgstr ""

#: glance/store/http.py:174
msgid "HTTP datastore could not find image at URI."
msgstr ""

#: glance/store/http.py:177
#, python-format
msgid "HTTP URL returned a %s status code."
msgstr ""

#: glance/store/http.py:184
#, python-format
msgid "The HTTP URL attempted to redirect with an invalid %s status code."
msgstr ""

#: glance/store/rbd.py:55
msgid ""
"RADOS images will be chunked into objects of this size (in megabytes). "
"For best performance, this should be a power of two."
msgstr ""

#: glance/store/rbd.py:59
msgid "RADOS pool in which images are stored."
msgstr ""

#: glance/store/rbd.py:61
msgid ""
"RADOS user to authenticate as (only applicable if using Cephx. If <None>,"
" a default will be chosen based on the client. section in "
"rbd_store_ceph_conf)."
msgstr ""

#: glance/store/rbd.py:65
msgid ""
"Ceph configuration file path. If <None>, librados will locate the default"
" config. If using cephx authentication, this file should include a "
"reference to the right keyring in a client.<USER> section."
msgstr ""

#: glance/store/rbd.py:111
msgid "URI must start with rbd://"
msgstr ""

#: glance/store/rbd.py:119
msgid "URI contains non-ascii characters"
msgstr ""

#: glance/store/rbd.py:131
msgid "URI must have exactly 1 or 4 components"
msgstr ""

#: glance/store/rbd.py:136
msgid "URI cannot contain empty components"
msgstr ""

#: glance/store/rbd.py:171 glance/store/rbd.py:295
#, python-format
msgid "RBD image %s does not exist"
msgstr ""

#: glance/store/rbd.py:198 glance/store/sheepdog.py:198
#: glance/store/sheepdog.py:214
#, python-format
msgid "Error in store configuration: %s"
msgstr ""

#: glance/store/rbd.py:331
msgid ""
"since image size is zero we will be doing resize-before-write for each "
"chunk which will be considerably slower than normal"
msgstr ""

#: glance/store/rbd.py:340
#, python-format
msgid "RBD image %s already exists"
msgstr ""

#: glance/store/s3.py:50
msgid "The host where the S3 server is listening."
msgstr ""

#: glance/store/s3.py:52
msgid "The S3 query token access key."
msgstr ""

#: glance/store/s3.py:54
msgid "The S3 query token secret key."
msgstr ""

#: glance/store/s3.py:56
msgid "The S3 bucket to be used to store the Glance data."
msgstr ""

#: glance/store/s3.py:58
msgid ""
"The local directory where uploads will be staged before they are "
"transferred into S3."
msgstr ""

#: glance/store/s3.py:61
msgid ""
"A boolean to determine if the S3 bucket should be created on upload if it"
" does not exist or if an error should be returned to the user."
msgstr ""

#: glance/store/s3.py:65
msgid ""
"The S3 calling format used to determine the bucket. Either subdomain or "
"path can be used."
msgstr ""

#: glance/store/s3.py:69
msgid ""
"What size, in MB, should S3 start chunking image files and do a multipart"
" upload in S3."
msgstr ""

#: glance/store/s3.py:73
msgid ""
"What multipart upload part size, in MB, should S3 use when uploading "
"parts. The size must be greater than or equal to 5M."
msgstr ""

#: glance/store/s3.py:77
msgid "The number of thread pools to perform a multipart upload in S3."
msgstr ""

#: glance/store/s3.py:198
msgid ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"s3://accesskey:secretkey@https://s3.amazonaws.com/bucket/key-id, you need"
" to change it to use the s3+https:// scheme, like so: "
"s3+https://accesskey:secretkey@s3.amazonaws.com/bucket/key-id"
msgstr ""

#: glance/store/s3.py:232
msgid "Badly formed S3 credentials"
msgstr ""

#: glance/store/s3.py:245
msgid "Badly formed S3 URI. Missing s3 service URL."
msgstr ""

#: glance/store/s3.py:248
msgid "Badly formed S3 URI"
msgstr ""

#: glance/store/s3.py:337
#, python-format
msgid ""
"s3_store_large_object_chunk_size must be at least %(_s3_ck_min)d MB. You "
"configured it as %(_s3_ck_size)d MB"
msgstr ""

#: glance/store/s3.py:347
#, python-format
msgid "s3_store_thread_pools must be a positive integer. %s"
msgstr ""

#: glance/store/s3.py:471
#, python-format
msgid "S3 already has an image at location %s"
msgstr ""

#: glance/store/s3.py:596
#, python-format
msgid "Failed to add image object to S3. key=%(obj_name)s"
msgstr ""

#: glance/store/s3.py:684
#, python-format
msgid ""
"Failed to add bucket to S3.\n"
"Got error from S3: %(e)s"
msgstr ""

#: glance/store/s3.py:688
#, python-format
msgid ""
"The bucket %(bucket)s does not exist in S3. Please set the "
"s3_store_create_bucket_on_put option to add bucket to S3 automatically."
msgstr ""

#: glance/store/sheepdog.py:43
msgid ""
"Images will be chunked into objects of this size (in megabytes). For best"
" performance, this should be a power of two."
msgstr ""

#: glance/store/sheepdog.py:47
msgid "Port of sheep daemon."
msgstr ""

#: glance/store/sheepdog.py:49
msgid "IP address of sheep daemon."
msgstr ""

#: glance/store/sheepdog.py:150
#, python-format
msgid "URI must start with '%s://'"
msgstr ""

#: glance/store/sheepdog.py:154
msgid "URI must contains well-formated image id"
msgstr ""

#: glance/store/sheepdog.py:204
#, python-format
msgid "Invalid address configuration of sheepdog store: %s"
msgstr ""

#: glance/store/sheepdog.py:234 glance/store/sheepdog.py:253
#: glance/store/sheepdog.py:314
#, python-format
msgid "Sheepdog image %s does not exist"
msgstr ""

#: glance/store/sheepdog.py:275
#, python-format
msgid "Sheepdog image %s already exists"
msgstr ""

#: glance/store/swift.py:53
msgid "Whether to use ServiceNET to communicate with the Swift storage servers."
msgstr ""

#: glance/store/swift.py:56
msgid ""
"Version of the authentication service to use. Valid versions are 2 for "
"keystone and 1 for swauth and rackspace. (deprecated)"
msgstr ""

#: glance/store/swift.py:60
msgid ""
"If True, swiftclient won't check for a valid SSL certificate when "
"authenticating."
msgstr ""

#: glance/store/swift.py:63
msgid ""
"The region of the swift endpoint to be used for single tenant. This "
"setting is only necessary if the tenant has multiple swift endpoints."
msgstr ""

#: glance/store/swift.py:67
msgid ""
"A string giving the endpoint type of the swift service to use (publicURL,"
" adminURL or internalURL). This setting is only used if "
"swift_store_auth_version is 2."
msgstr ""

#: glance/store/swift.py:72
msgid ""
"A string giving the service type of the swift service to use. This "
"setting is only used if swift_store_auth_version is 2."
msgstr ""

#: glance/store/swift.py:77
msgid ""
"Container within the account that the account should use for storing "
"images in Swift."
msgstr ""

#: glance/store/swift.py:81
msgid ""
"The size, in MB, that Glance will start chunking image files and do a "
"large object manifest in Swift."
msgstr ""

#: glance/store/swift.py:85
msgid ""
"The amount of data written to a temporary disk buffer during the process "
"of chunking the image file."
msgstr ""

#: glance/store/swift.py:88
msgid ""
"A boolean value that determines if we create the container if it does not"
" exist."
msgstr ""

#: glance/store/swift.py:91
msgid ""
"If set to True, enables multi-tenant storage mode which causes Glance "
"images to be stored in tenant specific Swift accounts."
msgstr ""

#: glance/store/swift.py:95
msgid ""
"A list of tenants that will be granted read/write access on all Swift "
"containers created by Glance in multi-tenant mode."
msgstr ""

#: glance/store/swift.py:99
msgid ""
"If set to False, disables SSL layer compression of https swift requests. "
"Setting to False may improve performance for images which are already in "
"a compressed format, eg qcow2."
msgstr ""

#: glance/store/swift.py:104
msgid ""
"The number of times a Swift download will be retried before the request "
"fails."
msgstr ""

#: glance/store/swift.py:126
#, python-format
msgid "Swift exception raised %s"
msgstr ""

#: glance/store/swift.py:131
#, python-format
msgid "Stopping Swift retries after %d attempts"
msgstr ""

#: glance/store/swift.py:136
#, python-format
msgid ""
"Retrying Swift connection (%(retries)d/%(max_retries)d) with "
"range=%(start)d-%(end)d"
msgstr ""

#: glance/store/swift.py:223
msgid "Badly formed Swift URI. Credentials not found foraccount reference"
msgstr ""

#: glance/store/swift.py:274
msgid "Badly formed Swift URI."
msgstr ""

#: glance/store/swift.py:293
msgid ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""

#: glance/store/swift.py:384
#, python-format
msgid "Swift could not find object %s."
msgstr ""

#: glance/store/swift.py:435
#, python-format
msgid "Failed to delete orphaned chunk %(container)s/%(chunk)s"
msgstr ""

#: glance/store/swift.py:496
msgid "Error during chunked upload to backend, deleting stale chunks"
msgstr ""

#: glance/store/swift.py:559
msgid "Swift already has an image at this location"
msgstr ""

#: glance/store/swift.py:561
#, python-format
msgid ""
"Failed to add object to Swift.\n"
"Got error from Swift: %(e)s"
msgstr ""

#: glance/store/swift.py:602 glance/store/swift.py:787
msgid "Swift could not find image at URI."
msgstr ""

#: glance/store/swift.py:626
#, python-format
msgid ""
"Failed to add container to Swift.\n"
"Got error from Swift: %(e)s"
msgstr ""

#: glance/store/swift.py:630
#, python-format
msgid ""
"The container %(container)s does not exist in Swift. Please set the "
"swift_store_create_container_on_put optionto add container to Swift "
"automatically."
msgstr ""

#: glance/store/swift.py:660
msgid "A value for swift_store_auth_address is required."
msgstr ""

#: glance/store/swift.py:673
msgid "A value for swift_store_ref_params is required."
msgstr ""

#: glance/store/swift.py:690
msgid "Location credentials are invalid"
msgstr ""

#: glance/store/swift.py:695
msgid "Location is missing user:password information."
msgstr ""

#: glance/store/swift.py:707
#, python-format
msgid "Badly formed tenant:user '%(user)s' in Swift URI"
msgstr ""

#: glance/store/swift.py:734
msgid "Multi-tenant Swift storage requires a context."
msgstr ""

#: glance/store/swift.py:738
msgid "Multi-tenant Swift storage requires a service catalog."
msgstr ""

#: glance/store/vmware_datastore.py:48
msgid ""
"ESX/ESXi or vCenter Server target system. The server value can be an IP "
"address or a DNS name."
msgstr ""

#: glance/store/vmware_datastore.py:51
msgid "Username for authenticating with VMware ESX/VC server."
msgstr ""

#: glance/store/vmware_datastore.py:54
msgid "Password for authenticating with VMware ESX/VC server."
msgstr ""

#: glance/store/vmware_datastore.py:59
msgid ""
"Inventory path to a datacenter. If the vmware_server_host specified is an"
" ESX/ESXi, the vmware_datacenter_path is optional. If specified, it "
"should be \"ha-datacenter\"."
msgstr ""

#: glance/store/vmware_datastore.py:64
msgid "Datastore associated with the datacenter."
msgstr ""

#: glance/store/vmware_datastore.py:67
msgid ""
"Number of times VMware ESX/VC server API must be retried upon connection "
"related issues."
msgstr ""

#: glance/store/vmware_datastore.py:71
msgid ""
"The interval used for polling remote tasks invoked on VMware ESX/VC "
"server."
msgstr ""

#: glance/store/vmware_datastore.py:75
msgid ""
"The name of the directory where the glance images will be stored in the "
"VMware datastore."
msgstr ""

#: glance/store/vmware_datastore.py:79
msgid "Allow to perform insecure SSL requests to ESX/VC."
msgstr ""

#: glance/store/vmware_datastore.py:189
#, python-format
msgid "URI must start with %s://"
msgstr ""

#: glance/store/vmware_datastore.py:204
msgid "Badly formed VMware datastore URI"
msgstr ""

#: glance/store/vmware_datastore.py:244
#, python-format
msgid "Could not find datastore %(ds_name)s in datacenter %(dc_path)s"
msgstr ""

#: glance/store/vmware_datastore.py:304 glance/store/vmware_datastore.py:312
#, python-format
msgid "Failed to upload content of image %(image)s"
msgstr ""

#: glance/store/vmware_datastore.py:308
#, python-format
msgid "Image file %(image_id)s already exists!"
msgstr ""

#: glance/store/vmware_datastore.py:383
#, python-format
msgid "Failed to delete image %(image)s content."
msgstr ""

#: glance/store/vmware_datastore.py:398
#, python-format
msgid "Failed to access image %(image)s content."
msgstr ""

#: glance/store/vmware_datastore.py:405
#, python-format
msgid "HTTP request returned a %(status)s status code."
msgstr ""

#: glance/store/vmware_datastore.py:412
#, python-format
msgid ""
"The HTTP URL %(path)s attempted to redirect with an invalid %(status)s "
"status code."
msgstr ""

#: glance/tests/unit/test_migrations.py:929
#, python-format
msgid "location: %s data lost"
msgstr ""

